events {}

http {
  server {
    listen 8000;
    server_name _;
    client_max_body_size 2m;

    location = /health {
      access_log off;
      add_header Content-Type text/plain;
      return 200 "ok\n";
    }

    location /auth/v1/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://auth:9999/;
    }

    location /rest/v1/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_pass http://rest:3000/;
    }

    location / {
      return 404;
    }
  }
}
